# Tourism Data Collection - Bipsa

# Tourism

In [32]:
!pip install pypdf

Collecting pypdf
  Downloading pypdf-6.14.2-py3-none-any.whl.metadata (7.2 kB)
Downloading pypdf-6.14.2-py3-none-any.whl (349 kB)
Installing collected packages: pypdf
Successfully installed pypdf-6.14.2

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
import pypdf

reader = pypdf.PdfReader('Nepal tourism statistics 2025_ibddtm6.pdf')

# Table 2.2 spans pages 29 and 30 (0-indexed)
page1_text = reader.pages[29].extract_text()
page2_text = reader.pages[30].extract_text()

print(page1_text)
print(page2_text)

12 | NEPAL TOURISM STATISTICS, 2025
TABLE 2.2: TOURIST ARRIVAL BY MONTH, 1995-2025
Y ear Jan. Feb. Mar. Apr. May Jun. Jul. Aug. Sep. Oct. Nov. Dec. Total
1995 22,207 28,240 34,219 33,994 27,843 25,650 23,980 27,686 30,569 46,845 35,782 26,380 363,395
1996 27,886 29,676 39,336 36,331 29,728 26,749 22,684 29,080 32,181 47,314 37,650 34,998 393,613
1997 25,585 32,861 43,177 35,229 33,456 26,367 26,091 35,549 31,981 56,272 40,173 35,116 421,857
1998 28,822 37,956 41,338 41,087 35,814 29,181 27,895 36,174 39,664 62,487 47,403 35,863 463,684
1999 29,752 38,134 46,218 40,774 42,712 31,049 27,193 38,449 44,117 66,543 48,865 37,698 491,504
2000 25,307 38,959 44,944 43,635 28,363 26,933 24,480 34,670 43,523 59,195 52,993 40,644 463,646
2001 30,454 38,680 46,709 39,083 28,345 13,030 18,329 25,322 31,170 41,245 30,282 18,588 361,237
2002 17,176 20,668 28,815 21,253 19,887 17,218 16,621 21,093 23,752 35,272 28,723 24,990 275,468
2003 21,215 24,349 27,737 25,851 22,704 20,351 22,661 27,568 28,724 45,459 38,398 33,115 338,132
2004 30,988 35,631 44,290 33,514 26,802 19,793 24,860 33,162 25,496 43,373 36,381 31,007 385,297
2005 25,477 20,338 29,875 23,414 25,541 22,608 23,996 36,910 36,066 51,498 41,505 38,170 375,398
2006 28,769 25,728 36,873 21,983 22,870 26,210 25,183 33,150 33,362 49,670 44,119 36,009 383,926
2007 33,192 39,934 54,722 40,942 35,854 31,316 35,437 44,683 45,552 70,644 52,273 42,156 526,705
2008 36,913 46,675 58,735 38,475 30,410 24,349 25,427 40,011 41,622 66,421 52,399 38,840 500,277
2009 29,278 40,617 49,567 43,337 30,037 31,749 30,432 44,174 42,771 72,522 54,423 41,049 509,956
2010 33,645 49,264 63,058 45,509 32,542 33,263 38,991 54,672 54,848 79,130 67,537 50,408 602,867
2011 42,622 56,339 67,565 59,751 46,202 46,115 42,661 71,398 63,033 96,996 83,460 60,073 736,215
2012 52,501 66,459 89,151 69,796 50,317 53,630 49,995 71,964 66,383 86,379 83,173 63,344 803,092
2013 47,846 67,264 88,697 65,152 52,834 54,599 54,011 68,478 66,755 99,426 75,485 57,069 797,616
2014 70196 69009 79914 80053 62558 50731 46546 59761 52894 80993 76305 61158 790,118
2015 38,616 58,523 79,187 65,729 17,569 18,368 22,967 38,606 39,050 56,584 58,304 45,467 538,970
2016 42,235 60,821 76,444 60,214 46,683 38,852 48,115 66,341 74,670 89,281 72,990 76,356 753002
2017 62,632 84,061 106,291 88,591 62,773 55,956 42,240 73,778 68,634 112,492 99,804 82,966 940218
NEPAL TOURISM STATISTICS, 2025| 13
Y ear Jan. Feb. Mar. Apr. May Jun. Jul. Aug. Sep. Oct. Nov. Dec. Total
2018 73,187 89,507 124,686 98,650 68,825 65,159 73,281 87,679 91,874 130,745 147,859 121,620 1,173,072
2019 81,273 102,423 127,351 109,399 78,329 74,883 70,916 94,749 92,604 134,096 130,302 100,866 1,197,191
2020 79,702 98,190 42,776 14 31 102 196 267 584 2,025 1,956 4,242 230,085
2021 8,874 9,266 15,254 22,732 1,531 1,187 3,093 6,093 9,907 23,338 26,135 23,552 150,962
2022 16975 19856 42152 61589 54093 46957 44462 41304 58314 88582 72653 67932 614869
2023 55074 73255 99426 98773 77703 72250 57726 67153 91012 117306 108630 96574 1014882
2024 79101 97423 128167 111382 90205 76733 64598 72717 96302 124391 114496 92033 1147548
2025 79990 99585 121632 116487 86216 76425 70193 88681 79981 128443 116552 98180 1162365
Source: Department of Immigration, Nepal

In [21]:
raw_2021_2025 = """2021 8,874 9,266 15,254 22,732 1,531 1,187 3,093 6,093 9,907 23,338 26,135 23,552 150,962
2022 16975 19856 42152 61589 54093 46957 44462 41304 58314 88582 72653 67932 614869
2023 55074 73255 99426 98773 77703 72250 57726 67153 91012 117306 108630 96574 1014882
2024 79101 97423 128167 111382 90205 76733 64598 72717 96302 124391 114496 92033 1147548
2025 79990 99585 121632 116487 86216 76425 70193 88681 79981 128443 116552 98180 1162365"""

In [22]:
import pandas as pd

months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
records = []
for line in raw_2021_2025.strip().split('\n'):
    parts = line.split()
    year = int(parts[0])
    nums = [int(p.replace(',','')) for p in parts[1:13]]
    for m, val in zip(months, nums):
        records.append({'year': year, 'month': m, 'tourist_arrivals': val})

df_tourism = pd.DataFrame(records)

In [23]:
df_tourism

    year month  tourist_arrivals
0   2021   Jan              8874
1   2021   Feb              9266
2   2021   Mar             15254
3   2021   Apr             22732
4   2021   May              1531
5   2021   Jun              1187
6   2021   Jul              3093
7   2021   Aug              6093
8   2021   Sep              9907
9   2021   Oct             23338
10  2021   Nov             26135
11  2021   Dec             23552
12  2022   Jan             16975
13  2022   Feb             19856
14  2022   Mar             42152
15  2022   Apr             61589
16  2022   May             54093
17  2022   Jun             46957
18  2022   Jul             44462
19  2022   Aug             41304
20  2022   Sep             58314
21  2022   Oct             88582
22  2022   Nov             72653
23  2022   Dec             67932
24  2023   Jan             55074
25  2023   Feb             73255
26  2023   Mar             99426
27  2023   Apr             98773
28  2023   May             77703
29  2023   Jun             72250
30  2023   Jul             57726
31  2023   Aug             67153
32  2023   Sep             91012
33  2023   Oct            117306
34  2023   Nov            108630
35  2023   Dec             96574
36  2024   Jan             79101
37  2024   Feb             97423
38  2024   Mar            128167
39  2024   Apr            111382
40  2024   May             90205
41  2024   Jun             76733
42  2024   Jul             64598
43  2024   Aug             72717
44  2024   Sep             96302
45  2024   Oct            124391
46  2024   Nov            114496
47  2024   Dec             92033
48  2025   Jan             79990
49  2025   Feb             99585
50  2025   Mar            121632
51  2025   Apr            116487
52  2025   May             86216
53  2025   Jun             76425
54  2025   Jul             70193
55  2025   Aug             88681
56  2025   Sep             79981
57  2025   Oct            128443
58  2025   Nov            116552
59  2025   Dec             98180

In [24]:
print(df_tourism.shape)  # should be (60, 3)

(60, 3)

In [25]:
df_tourism.to_csv('nepal_tourism_monthly_2021_2025.csv', index=False)

In [9]:
import pypdf

reader = pypdf.PdfReader('Nepal tourism statistics 2025_ibddtm6.pdf')

# Table 2.2 spans pages 29 and 30 (0-indexed)
page1_text = reader.pages[29].extract_text()
page2_text = reader.pages[30].extract_text()

print(page1_text)
print(page2_text)

12 | NEPAL TOURISM STATISTICS, 2025
TABLE 2.2: TOURIST ARRIVAL BY MONTH, 1995-2025
Y ear Jan. Feb. Mar. Apr. May Jun. Jul. Aug. Sep. Oct. Nov. Dec. Total
1995 22,207 28,240 34,219 33,994 27,843 25,650 23,980 27,686 30,569 46,845 35,782 26,380 363,395
1996 27,886 29,676 39,336 36,331 29,728 26,749 22,684 29,080 32,181 47,314 37,650 34,998 393,613
1997 25,585 32,861 43,177 35,229 33,456 26,367 26,091 35,549 31,981 56,272 40,173 35,116 421,857
1998 28,822 37,956 41,338 41,087 35,814 29,181 27,895 36,174 39,664 62,487 47,403 35,863 463,684
1999 29,752 38,134 46,218 40,774 42,712 31,049 27,193 38,449 44,117 66,543 48,865 37,698 491,504
2000 25,307 38,959 44,944 43,635 28,363 26,933 24,480 34,670 43,523 59,195 52,993 40,644 463,646
2001 30,454 38,680 46,709 39,083 28,345 13,030 18,329 25,322 31,170 41,245 30,282 18,588 361,237
2002 17,176 20,668 28,815 21,253 19,887 17,218 16,621 21,093 23,752 35,272 28,723 24,990 275,468
2003 21,215 24,349 27,737 25,851 22,704 20,351 22,661 27,568 28,724 45,459 38,398 33,115 338,132
2004 30,988 35,631 44,290 33,514 26,802 19,793 24,860 33,162 25,496 43,373 36,381 31,007 385,297
2005 25,477 20,338 29,875 23,414 25,541 22,608 23,996 36,910 36,066 51,498 41,505 38,170 375,398
2006 28,769 25,728 36,873 21,983 22,870 26,210 25,183 33,150 33,362 49,670 44,119 36,009 383,926
2007 33,192 39,934 54,722 40,942 35,854 31,316 35,437 44,683 45,552 70,644 52,273 42,156 526,705
2008 36,913 46,675 58,735 38,475 30,410 24,349 25,427 40,011 41,622 66,421 52,399 38,840 500,277
2009 29,278 40,617 49,567 43,337 30,037 31,749 30,432 44,174 42,771 72,522 54,423 41,049 509,956
2010 33,645 49,264 63,058 45,509 32,542 33,263 38,991 54,672 54,848 79,130 67,537 50,408 602,867
2011 42,622 56,339 67,565 59,751 46,202 46,115 42,661 71,398 63,033 96,996 83,460 60,073 736,215
2012 52,501 66,459 89,151 69,796 50,317 53,630 49,995 71,964 66,383 86,379 83,173 63,344 803,092
2013 47,846 67,264 88,697 65,152 52,834 54,599 54,011 68,478 66,755 99,426 75,485 57,069 797,616
2014 70196 69009 79914 80053 62558 50731 46546 59761 52894 80993 76305 61158 790,118
2015 38,616 58,523 79,187 65,729 17,569 18,368 22,967 38,606 39,050 56,584 58,304 45,467 538,970
2016 42,235 60,821 76,444 60,214 46,683 38,852 48,115 66,341 74,670 89,281 72,990 76,356 753002
2017 62,632 84,061 106,291 88,591 62,773 55,956 42,240 73,778 68,634 112,492 99,804 82,966 940218
NEPAL TOURISM STATISTICS, 2025| 13
Y ear Jan. Feb. Mar. Apr. May Jun. Jul. Aug. Sep. Oct. Nov. Dec. Total
2018 73,187 89,507 124,686 98,650 68,825 65,159 73,281 87,679 91,874 130,745 147,859 121,620 1,173,072
2019 81,273 102,423 127,351 109,399 78,329 74,883 70,916 94,749 92,604 134,096 130,302 100,866 1,197,191
2020 79,702 98,190 42,776 14 31 102 196 267 584 2,025 1,956 4,242 230,085
2021 8,874 9,266 15,254 22,732 1,531 1,187 3,093 6,093 9,907 23,338 26,135 23,552 150,962
2022 16975 19856 42152 61589 54093 46957 44462 41304 58314 88582 72653 67932 614869
2023 55074 73255 99426 98773 77703 72250 57726 67153 91012 117306 108630 96574 1014882
2024 79101 97423 128167 111382 90205 76733 64598 72717 96302 124391 114496 92033 1147548
2025 79990 99585 121632 116487 86216 76425 70193 88681 79981 128443 116552 98180 1162365
Source: Department of Immigration, Nepal

In [10]:
raw_tourism = """2021 8,874 9,266 15,254 22,732 1,531 1,187 3,093 6,093 9,907 23,338 26,135 23,552 150,962
2022 16975 19856 42152 61589 54093 46957 44462 41304 58314 88582 72653 67932 614869
2023 55074 73255 99426 98773 77703 72250 57726 67153 91012 117306 108630 96574 1014882
2024 79101 97423 128167 111382 90205 76733 64598 72717 96302 124391 114496 92033 1147548
2025 79990 99585 121632 116487 86216 76425 70193 88681 79981 128443 116552 98180 1162365"""

months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
records = []
for line in raw_tourism.strip().split('\n'):
    parts = line.split()
    year = int(parts[0])
    nums = [int(p.replace(',','')) for p in parts[1:13]]
    for m, val in zip(months, nums):
        records.append({'year': year, 'month': m, 'tourist_arrivals': val})

df_tourism = pd.DataFrame(records)

In [11]:
df_tourism

    year month  tourist_arrivals
0   2021   Jan              8874
1   2021   Feb              9266
2   2021   Mar             15254
3   2021   Apr             22732
4   2021   May              1531
5   2021   Jun              1187
6   2021   Jul              3093
7   2021   Aug              6093
8   2021   Sep              9907
9   2021   Oct             23338
10  2021   Nov             26135
11  2021   Dec             23552
12  2022   Jan             16975
13  2022   Feb             19856
14  2022   Mar             42152
15  2022   Apr             61589
16  2022   May             54093
17  2022   Jun             46957
18  2022   Jul             44462
19  2022   Aug             41304
20  2022   Sep             58314
21  2022   Oct             88582
22  2022   Nov             72653
23  2022   Dec             67932
24  2023   Jan             55074
25  2023   Feb             73255
26  2023   Mar             99426
27  2023   Apr             98773
28  2023   May             77703
29  2023   Jun             72250
30  2023   Jul             57726
31  2023   Aug             67153
32  2023   Sep             91012
33  2023   Oct            117306
34  2023   Nov            108630
35  2023   Dec             96574
36  2024   Jan             79101
37  2024   Feb             97423
38  2024   Mar            128167
39  2024   Apr            111382
40  2024   May             90205
41  2024   Jun             76733
42  2024   Jul             64598
43  2024   Aug             72717
44  2024   Sep             96302
45  2024   Oct            124391
46  2024   Nov            114496
47  2024   Dec             92033
48  2025   Jan             79990
49  2025   Feb             99585
50  2025   Mar            121632
51  2025   Apr            116487
52  2025   May             86216
53  2025   Jun             76425
54  2025   Jul             70193
55  2025   Aug             88681
56  2025   Sep             79981
57  2025   Oct            128443
58  2025   Nov            116552
59  2025   Dec             98180

In [14]:
df_tourism.to_csv("grdv_tourism_monthly_clean.csv", index=False)